#!/usr/bin/env bash

script_version=$(git show HEAD:pre-commit | grep -E "^SCRIPT_VERSION=\d+")
new_script_version=$(grep -E "^SCRIPT_VERSION=\d+" pre-commit)

echo "    script_version: $script_version"
echo "new_script_version: $new_script_version"

((new_script_version > script_version))
